apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-homepage
  namespace: {{ .Values.namespace }}
  labels:
    component: homepage
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      component: homepage
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: homepage
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-environment-variables
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /
              port: http
